package #{class.package};

import org.romaframework.frontend.domain.entity.ComposedEntityInstance;

import #{domain.package}#{domain.class};

/**
 * Class used to display #{domain.class} instances as result set of the searches executed in #{crud.class}Main. It uses
 * the Extension-by-composition pattern.
 * <br/><br/>
 * This class is generated by Roma Meta Framework CRUD wizard.       
 * <br/><br/>
 * @author #{author}     
 */
public class #{crud.class}Listable extends ComposedEntityInstance<#{domain.class}> {
  public #{crud.class}Listable(#{domain.class} iEntity) {
    super(iEntity);
  }

  // INSERT HERE GETTER METHOD TO VIEW ADDITIONAL FIELDS
}
