package #{class.package};

import org.romaframework.core.Roma;
import org.romaframework.frontend.domain.crud.CRUDFilter;

import #{domain.package}#{domain.class};
import #{project.package}.factory.#{domain.class}Factory;

/**
 * Filter class able to extends the #{domain.class} using the Extension-by-composition pattern. This class
 * is used in #{crud.class}Main to filter searches using the QueryByExample pattern. 
 * <br/><br/>
 * This class is generated by Roma Meta Framework CRUD wizard.  
 * <br/><br/>
 * @author #{author}     
 */ 
public class #{crud.class}Filter extends CRUDFilter<#{domain.class}> {
  public #{crud.class}Filter() {
    this(Roma.component(#{domain.class}Factory.class).create());
  }

  public #{crud.class}Filter(#{domain.class} i#{domain.class}) {
    super(i#{domain.class});
  }
}
