package #{project.package}.factory;

import #{domain.package}.#{crud.class};

import org.romaframework.core.factory.AbstractFactory;

/**
 * Factory class for #{crud.class} entity. It's registered in the IoC configuration files and is used by Roma components to create objects of kind #{crud.class}. 
 * <br/>Use EntityHelper.createObject() to create objects using the its factory.
 * <br/>This class was generated by Roma Meta Framework CRUD wizard.
 * @see EntityHelper  
 */ 
public class #{crud.class}Factory extends AbstractFactory<#{crud.class}> {
  @Override
  public #{crud.class} create() {
    return new #{crud.class}();
  }
}
