package #{project.package}.repository;

import #{domain.package}#{domain.class};

import java.util.List;

import org.romaframework.core.repository.PersistenceAspectRepository;

/**
 * Repository class for #{domain.class} entity. By default it extends the
 * PersistenceAspectRepository class that delegates the execution of all
 * commands to the PersistenceAspect.
 * <br/><br/>
 * This class was generated by Roma Meta Framework CRUD wizard.       
 */ 
public class #{crud.class}Repository extends PersistenceAspectRepository<#{domain.class}> {
	
}
