package #{class.package};

import org.romaframework.core.Roma;
import org.romaframework.frontend.domain.crud.CRUDFilter;

import #{domain.package}.#{crud.class};
import #{project.package}.factory.#{crud.class}Factory;

/**
 * Filter class able to extends the #{crud.class} using the Extension-by-composition pattern. This class
 * is used in #{crud.class}Main to filter searches using the QueryByExample pattern. 
 * <br/><br/>
 * This class is generated by Roma Meta Framework CRUD wizard.  
 * <br/><br/>
 * @author #{author}     
 */ 
public class #{crud.class}Filter extends CRUDFilter<#{crud.class}> {
  public #{crud.class}Filter() {
    this(Roma.component(#{crud.class}Factory.class).create());
  }

  public #{crud.class}Filter(#{crud.class} i#{crud.class}) {
    super(i#{crud.class});
  }
}
